### ISSUE TITLE
Cannot turn off sounds

### ISSUE THREAD

**Issue by MrJoshuaT** [Syrent/VelocityVanish#138]
### Server backend version

Paper 1.19.3

### Server Velocity version

3.2.0-SNAPSHOT

### VelocityVanish version

3.18.1

### Describe the bug

Cannot turn off sounds. Trying to set `sounds.command` or `sounds.vanish` or `sounds.unvanish` to `""` produces a startup exception.

java.lang.ExceptionInInitializerError: null
        at ir.syrent.velocityvanish.spigot.VelocityVanishSpigot.initializeInstances(VelocityVanishSpigot.kt:127) ~[VelocityVanish v3.18.1.jar:?]
        at ir.syrent.velocityvanish.spigot.VelocityVanishSpigot.onEnable(VelocityVanishSpigot.kt:45) ~[VelocityVanish v3.18.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578) ~[paper-1.19.3.jar:git-Paper-399]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492) ~[paper-1.19.3.jar:git-Paper-399]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.19.3.jar:git-Paper-399]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-399]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.3.jar:git-Paper-399]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-399]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-399]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: No enum constant ir.syrent.velocityvanish.xseries.XSound.
        at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
        at ir.syrent.velocityvanish.xseries.XSound.valueOf(XSound.java:61) ~[VelocityVanish v3.18.1.jar:?]
        at ir.syrent.velocityvanish.spigot.storage.Settings.load(Settings.kt:83) ~[VelocityVanish v3.18.1.jar:?]
        at ir.syrent.velocityvanish.spigot.storage.Settings.<clinit>(Settings.kt:55) ~[VelocityVanish v3.18.1.jar:?]
        ... 13 more

### Expected behavior

Should be able to turn off sounds

### Steps to reproduce

Change settings.yml to:
sounds:
  command: ""
  vanish: ""
  unvanish: ""

Restart server

See error in startup log

### Checklist

- [X] I am running latest version of the plugin on both Velocity and Spigot
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them

**Comment by Syrent** [comment]
Try this version:
[VelocityVanish v3.18.1.zip](https://github.com/Syrent/VelocityVanish/files/11066404/VelocityVanish.v3.18.1.zip)

**Comment by Syrent** [comment]
Fixed in 3.18.2
