### ISSUE TITLE
Folia UnsupportedOperationException

### ISSUE THREAD

**Issue by mani1232** [Syrent/VelocityVanish#242]
### Server backend version

Folia 1.20.1

### Server backend Java version

graalvm:17-EE

### Server Velocity version

latest

### Server Velocity Java version

graalvm:17-EE

### VelocityVanish version

latest from modrith

### Describe the bug

use /vanish and get error
```
[03:06:05 INFO]: UUID of player mani1232 is 60da242a-a56e-373d-8b6d-d76638e500c0
[03:06:06 WARN]: [VelocityVanish] Global task for VelocityVanish v3.26.0-build.16-e94d411 generated an exception
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.v1_20_R1.scoreboard.CraftScoreboard.registerNewTeam(CraftScoreboard.java:202) ~[kaiiju-1.20.1.jar:git-Kaiiju-"ad96ea2"]
        at ir.syrent.velocityvanish.spigot.core.VanishManager.denyPush(VanishManager.kt:148) ~[VelocityVanish_3.26.0-build.16-e94d411.jar:?]
        at ir.syrent.velocityvanish.spigot.core.VanishManager.vanish(VanishManager.kt:234) ~[VelocityVanish_3.26.0-build.16-e94d411.jar:?]
        at ir.syrent.velocityvanish.spigot.core.VanishManager.vanish(VanishManager.kt:159) ~[VelocityVanish_3.26.0-build.16-e94d411.jar:?]
        at ir.syrent.velocityvanish.spigot.listener.PlayerJoinListener.onPlayerJoin$lambda$2(PlayerJoinListener.kt:52) ~[VelocityVanish_3.26.0-build.16-e94d411.jar:?]
        at ir.syrent.velocityvanish.spigot.ruom.Ruom.runSync$lambda$1(Ruom.kt:112) ~[VelocityVanish_3.26.0-build.16-e94d411.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[kaiiju-1.20.1.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[kaiiju-1.20.1.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:294) ~[kaiiju-1.20.1.jar:git-Kaiiju-"ad96ea2"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:149) ~[kaiiju-1.20.1.jar:git-Kaiiju-"ad96ea2"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[kaiiju-1.20.1.jar:git-Kaiiju-"ad96ea2"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[kaiiju-1.20.1.jar:git-Kaiiju-"ad96ea2"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
 ```
and
```
[03:06:27 INFO]: mani1232 issued server command: /vanish
[03:06:27 WARN]: java.lang.UnsupportedOperationException
[03:06:27 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scoreboard.CraftScoreboard.registerNewTeam(CraftScoreboard.java:202)
[03:06:27 WARN]:        at VelocityVanish_3.26.0-build.16-e94d411.jar//ir.syrent.velocityvanish.spigot.core.VanishManager.denyPush(VanishManager.kt:148)
[03:06:27 WARN]:        at VelocityVanish_3.26.0-build.16-e94d411.jar//ir.syrent.velocityvanish.spigot.core.VanishManager.vanish(VanishManager.kt:234)
[03:06:27 WARN]:        at VelocityVanish_3.26.0-build.16-e94d411.jar//ir.syrent.velocityvanish.spigot.command.VanishCommand._init_$lambda$26(VanishCommand.kt:163)
[03:06:27 WARN]:        at VelocityVanish_3.26.0-build.16-e94d411.jar//ir.syrent.velocityvanish.dependencies.cloud.commandframework.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95)
[03:06:27 WARN]:        at VelocityVanish_3.26.0-build.16-e94d411.jar//ir.syrent.velocityvanish.dependencies.cloud.commandframework.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:123)
[03:06:27 WARN]:        at VelocityVanish_3.26.0-build.16-e94d411.jar//ir.syrent.velocityvanish.dependencies.cloud.commandframework.CommandManager.executeCommand(CommandManager.java:188)
[03:06:27 WARN]:        at VelocityVanish_3.26.0-build.16-e94d411.jar//ir.syrent.velocityvanish.dependencies.cloud.commandframework.bukkit.BukkitCommand.execute(BukkitCommand.java:116)
[03:06:27 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[03:06:27 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1048)
[03:06:27 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[03:06:27 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[03:06:27 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:324)
[03:06:27 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:308)
[03:06:27 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2393)
[03:06:27 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$16(PlayerConnection.java:2353)
[03:06:27 WARN]:        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173)
[03:06:27 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1524)
[03:06:27 WARN]:        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360)
[03:06:27 WARN]:        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385)
[03:06:27 WARN]:        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525)
[03:06:27 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Expected behavior

use /vanish and get error

### Steps to reproduce

use /vanish and get error

### LuckPerms webview link

?

### VelocityVanish's configuration file

not edited

### Plugins

![image](https://github.com/Syrent/VelocityVanish/assets/70480001/d7b4bab5-0478-4550-af2e-2e207da6d694)

### Checklist

- [X] I am running the latest version of the plugin on both Velocity and Spigot
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I tried the plugin on a fresh server and it didn't work (Or it worked but I know exactly which plugin it's incompatible with)
- [ ] I ticked all of the boxes without actually reading them

**Comment by Syrent** [comment]
Try the latest Folia version.
Everything seems to work fine on it:
![image](https://github.com/Syrent/VelocityVanish/assets/56670179/139da3cb-7a60-4dd4-8515-71af76aad491)
```
[14:35:37 INFO]: UUID of player Syrent231 is 97c79d06-fdbc-307d-88e5-bbf498a19dda
[14:35:38 INFO]: Syrent231[/127.0.0.1:2791] logged in with entity id 34 at ([world]491.1076267345507, 142.0, -1394.6005036812555)
[14:35:55 INFO]: Syrent231 issued server command: /velocityvanish
[14:35:56 INFO]: Syrent231 issued server command: /velocityvanish
[14:36:10 INFO]: Syrent231 issued server command: /folia
[14:36:12 INFO]: Syrent231 issued server command: /paper version
```

**Comment by mani1232** [comment]
try /vanish , not /velocityvanish, folia and forks dont support scoreboard

**Comment by mani1232** [comment]
And you install it both on proxy and server?

**Comment by Syrent** [comment]
Same result on Velocity and `/vanish` command

## Velocity console:
![image](https://github.com/Syrent/VelocityVanish/assets/56670179/7eacccf0-1364-45ae-85f5-03b01effe3b9)
## Folia console:
![image](https://github.com/Syrent/VelocityVanish/assets/56670179/76dc7901-2c02-453d-bd32-088a9c91e1af)
## Minecraft view:
![image](https://github.com/Syrent/VelocityVanish/assets/56670179/bf860c07-8666-4141-9ea3-99fe3a33442a)

Velocity version: Velocity 3.2.0-SNAPSHOT (git-19abb909-b265)
Folia version: git-Folia-15 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: f6e91e9)
