### ISSUE TITLE
Failed to download library

### ISSUE THREAD

**Issue by cmx-root** [Syrent/VelocityVanish#346]
```
[08:50:27 WARN]: java.lang.RuntimeException: Failed to download library 'me.kcra.takenaka:generator-accessor-runtime:1.2.0'
[08:50:27 WARN]:        at SayanVanish-1.5.0-SNAPSHOT-build.196-44b56b6-bukkit.jar//com.alessiodp.libby.LibraryManager.downloadLibrary(LibraryManager.java:635)
[08:50:27 WARN]:        at SayanVanish-1.5.0-SNAPSHOT-build.196-44b56b6-bukkit.jar//com.alessiodp.libby.LibraryManager.loadLibrary(LibraryManager.java:719)
[08:50:27 WARN]:        at SayanVanish-1.5.0-SNAPSHOT-build.196-44b56b6-bukkit.jar//org.sayandev.loader.common.StickyNoteLoader.lambda$loadCachedDependencies$6(StickyNoteLoader.java:154)
[08:50:27 WARN]:        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[08:50:27 WARN]:        at SayanVanish-1.5.0-SNAPSHOT-build.196-44b56b6-bukkit.jar//org.sayandev.loader.common.StickyNoteLoader.loadCachedDependencies(StickyNoteLoader.java:151)
[08:50:27 WARN]:        at SayanVanish-1.5.0-SNAPSHOT-build.196-44b56b6-bukkit.jar//org.sayandev.loader.common.StickyNoteLoader.load(StickyNoteLoader.java:84)
[08:50:27 WARN]:        at SayanVanish-1.5.0-SNAPSHOT-build.196-44b56b6-bukkit.jar//org.sayandev.sayanvanish.lib.stickynote.loader.bukkit.StickyNoteBukkitLoader.<init>(StickyNoteBukkitLoader.java:53)
[08:50:27 WARN]:        at SayanVanish-1.5.0-SNAPSHOT-build.196-44b56b6-bukkit.jar//org.sayandev.sayanvanish.lib.stickynote.loader.bukkit.StickyNoteBukkitLoader.<init>(StickyNoteBukkitLoader.java:21)
[08:50:27 WARN]:        at SayanVanish-1.5.0-SNAPSHOT-build.196-44b56b6-bukkit.jar//org.sayandev.sayanvanish.bukkit.SayanVanish.onEnable(SayanVanish.kt:25)
[08:50:27 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[08:50:27 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[08:50:27 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[08:50:27 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[08:50:27 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640)
[08:50:27 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589)
[08:50:27 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753)
[08:50:27 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515)
[08:50:27 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
[08:50:27 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
[08:50:27 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[08:50:27 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by Syrent** [comment]
restart the server and try again
