### ISSUE TITLE
Invalid Errors 

### ISSUE THREAD

**Issue by TheWylot** [Syrent/VelocityVanish#40]
### Server backend version

Purpur 1.17.1

### Server Velocity version

Velocity 3.1.2 B184

### VelocityVanish version

3.8.0

### Describe the bug

there is an error on startup of server

### Expected behavior

java.lang.NoSuchMethodError: 'net.kyori.adventure.text.minimessage.MiniMessage net.kyori.adventure.text.minimessage.MiniMessage.miniMessage()'
        at ir.syrent.velocityvanish.utils.StringUtilsKt.component(StringUtils.kt:8) ~[VelocityVanish.v3.8.0.jar:?]
        at ir.syrent.velocityvanish.spigot.VelocityVanishSpigot.sendConsoleMessage(VelocityVanishSpigot.kt:143) ~[VelocityVanish.v3.8.0.jar:?]
        at ir.syrent.velocityvanish.spigot.VelocityVanishSpigot.sendFiglet(VelocityVanishSpigot.kt:57) ~[VelocityVanish.v3.8.0.jar:?]
        at ir.syrent.velocityvanish.spigot.VelocityVanishSpigot.onEnable(VelocityVanishSpigot.kt:42) ~[VelocityVanish.v3.8.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.frankheijden.serverutils.bukkit.managers.BukkitPluginManager.enableOrderedPlugins(BukkitPluginManager.java:184) ~[Serverutils.jar:?]
        at net.frankheijden.serverutils.common.managers.AbstractPluginManager.enablePlugins(AbstractPluginManager.java:105) ~[Serverutils.jar:?]
        at net.frankheijden.serverutils.common.managers.AbstractPluginManager.reloadPlugins(AbstractPluginManager.java:219) ~[Serverutils.jar:?]
        at net.frankheijden.serverutils.common.commands.CommandServerUtils.handleReloadPlugin(CommandServerUtils.java:243) ~[Serverutils.jar:?]
        at net.frankheijden.serverutils.dependencies.cloud.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:58) ~[Serverutils.jar:?]
        at net.frankheijden.serverutils.dependencies.cloud.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:120) ~[Serverutils.jar:?]
        at net.frankheijden.serverutils.dependencies.cloud.CommandManager.executeCommand(CommandManager.java:177) ~[Serverutils.jar:?]
        at net.frankheijden.serverutils.dependencies.cloud.bukkit.BukkitCommand.execute(BukkitCommand.java:110) ~[Serverutils.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:832) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:567) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:529) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1507) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1300) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:30:28 INFO]: [VelocityVanish] Disabling VelocityVanish v3.8.0
[15:30:28 INFO]: An error occurred, please check the console!

### Steps to reproduce

Step 1: run a 1.17.1 server
Step 2: install VelocityVanish on it

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them

**Comment by Syrent** [comment]
The problem is Purpur 1.17.1 uses an outdated version of MiniMessage

Getting MiniMessage instance in legacy versions:
```kotlin
MiniMessage.get()
```
Latest version:
```kotlin
MiniMessage.miniMessage()
```

This bug is unfixable with the current plugin codebase
I suggest you to upgrade your server version to 1.19.2

**Comment by Syrent** [comment]
Quick note: Relocating adventure packages will fix problems on backend servers but makes new problems in Velocity.

**Comment by Syrent** [comment]
Using reflection can fix the problem but i don't think it's nessasseray to add support for versions lie 1.16 or 1.17
